# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vinith/dk4/lab5/coe4dk4_lab_2_2025/coe4dk4_lab_2_2025

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vinith/dk4/lab5/coe4dk4_lab_2_2025/coe4dk4_lab_2_2025

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vinith/dk4/lab5/coe4dk4_lab_2_2025/coe4dk4_lab_2_2025/CMakeFiles /home/vinith/dk4/lab5/coe4dk4_lab_2_2025/coe4dk4_lab_2_2025//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vinith/dk4/lab5/coe4dk4_lab_2_2025/coe4dk4_lab_2_2025/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named run

# Build rule for target.
run: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run
.PHONY : run

# fast build rule for target.
run/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/build
.PHONY : run/fast

cleanup_memory.o: cleanup_memory.c.o
.PHONY : cleanup_memory.o

# target to build an object file
cleanup_memory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/cleanup_memory.c.o
.PHONY : cleanup_memory.c.o

cleanup_memory.i: cleanup_memory.c.i
.PHONY : cleanup_memory.i

# target to preprocess a source file
cleanup_memory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/cleanup_memory.c.i
.PHONY : cleanup_memory.c.i

cleanup_memory.s: cleanup_memory.c.s
.PHONY : cleanup_memory.s

# target to generate assembly for a file
cleanup_memory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/cleanup_memory.c.s
.PHONY : cleanup_memory.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/main.c.s
.PHONY : main.c.s

output.o: output.c.o
.PHONY : output.o

# target to build an object file
output.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/output.c.o
.PHONY : output.c.o

output.i: output.c.i
.PHONY : output.i

# target to preprocess a source file
output.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/output.c.i
.PHONY : output.c.i

output.s: output.c.s
.PHONY : output.s

# target to generate assembly for a file
output.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/output.c.s
.PHONY : output.c.s

packet_arrival.o: packet_arrival.c.o
.PHONY : packet_arrival.o

# target to build an object file
packet_arrival.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/packet_arrival.c.o
.PHONY : packet_arrival.c.o

packet_arrival.i: packet_arrival.c.i
.PHONY : packet_arrival.i

# target to preprocess a source file
packet_arrival.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/packet_arrival.c.i
.PHONY : packet_arrival.c.i

packet_arrival.s: packet_arrival.c.s
.PHONY : packet_arrival.s

# target to generate assembly for a file
packet_arrival.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/packet_arrival.c.s
.PHONY : packet_arrival.c.s

packet_transmission.o: packet_transmission.c.o
.PHONY : packet_transmission.o

# target to build an object file
packet_transmission.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/packet_transmission.c.o
.PHONY : packet_transmission.c.o

packet_transmission.i: packet_transmission.c.i
.PHONY : packet_transmission.i

# target to preprocess a source file
packet_transmission.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/packet_transmission.c.i
.PHONY : packet_transmission.c.i

packet_transmission.s: packet_transmission.c.s
.PHONY : packet_transmission.s

# target to generate assembly for a file
packet_transmission.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/packet_transmission.c.s
.PHONY : packet_transmission.c.s

simlib.o: simlib.c.o
.PHONY : simlib.o

# target to build an object file
simlib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/simlib.c.o
.PHONY : simlib.c.o

simlib.i: simlib.c.i
.PHONY : simlib.i

# target to preprocess a source file
simlib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/simlib.c.i
.PHONY : simlib.c.i

simlib.s: simlib.c.s
.PHONY : simlib.s

# target to generate assembly for a file
simlib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run.dir/build.make CMakeFiles/run.dir/simlib.c.s
.PHONY : simlib.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... run"
	@echo "... cleanup_memory.o"
	@echo "... cleanup_memory.i"
	@echo "... cleanup_memory.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... output.o"
	@echo "... output.i"
	@echo "... output.s"
	@echo "... packet_arrival.o"
	@echo "... packet_arrival.i"
	@echo "... packet_arrival.s"
	@echo "... packet_transmission.o"
	@echo "... packet_transmission.i"
	@echo "... packet_transmission.s"
	@echo "... simlib.o"
	@echo "... simlib.i"
	@echo "... simlib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

